# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (5)
# #########################################################################

class Compute(BaseModel):
    tool: typing.Optional[typing_extensions.Literal['compute']] = Field(default=None, description='Must be the literal string \'compute\'.')
    expression: typing.Optional[str] = Field(default=None, description='Python math expression, e.g. \'round(47.50 * 0.18, 2)\'.')

class Resume(BaseModel):
    name: typing.Optional[str] = None
    email: typing.Optional[str] = None
    experience: typing.List[str]
    skills: typing.List[str]

class SkillOption(BaseModel):
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None

class SkillResult(BaseModel):
    response: typing.Optional[str] = Field(default=None, description='Response text for the user. If a tool is needed, explain what you\'re computing but don\'t guess the answer.')
    tool_request: typing.Optional["Compute"] = Field(default=None, description='Optional tool call. Null if no tool is needed.')

class SkillSelection(BaseModel):
    selected_skill: typing.Optional[str] = Field(default=None, description='Skill name to activate, or null if none match.')
    reasoning: typing.Optional[str] = Field(default=None, description='One-sentence explanation.')

# #########################################################################
# Generated type aliases (1)
# #########################################################################


ToolRequest: typing_extensions.TypeAlias = typing.Optional["Compute"]
