# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (5)
# #########################################################################

class Resume(BaseModel):
    name: typing.Optional[str] = None
    email: typing.Optional[str] = None
    experience: typing.List[str]
    skills: typing.List[str]

class SkillOption(BaseModel):
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None

class SkillResult(BaseModel):
    plain_summary: typing.Optional[str] = Field(default=None, description='Plain English explanation of what\'s happening, for the user.')
    messages: typing.List["StaffMessage"] = Field(description='Messages to send to staff. May be empty for pure info lookups.')
    action: typing.Optional[types.ActionType] = Field(default=None, description='Action to take if the user confirms.')
    action_item_id: typing.Optional[str] = Field(default=None, description='Boat code for the action, e.g. \'TOV-001\'. Null if not applicable.')

class SkillSelection(BaseModel):
    selected_skill: typing.Optional[str] = Field(default=None, description='Skill name to activate, or null if none match.')
    reasoning: typing.Optional[str] = Field(default=None, description='Why this skill was chosen (or why none matched).')

class StaffMessage(BaseModel):
    recipient: typing.Optional[str] = Field(default=None, description='Staff member name: \'Captain Brillig\', \'Mimsy\', or \'The Bandersnatch\'.')
    message: typing.Optional[str] = Field(default=None, description='The drafted message in the recipient\'s required style and terminology.')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
