# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        client: typing.Optional[str] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if client is not None:
            options["client"] = client
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    def Chat(self, query: str,
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.Chat(query=query,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="Chat", args={
                "query": query,
            })
            return typing.cast(str, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ExecuteSkill(self, query: str,skill_instructions: str,available_tools: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> types.SkillResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ExecuteSkill(query=query,skill_instructions=skill_instructions,available_tools=available_tools,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ExecuteSkill", args={
                "query": query,"skill_instructions": skill_instructions,"available_tools": available_tools,
            })
            return typing.cast(types.SkillResult, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Resume:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ExtractResume(resume=resume,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractResume", args={
                "resume": resume,
            })
            return typing.cast(types.Resume, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def FinishWithToolResult(self, query: str,skill_instructions: str,partial_response: str,tool_name: str,tool_result: str,
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.FinishWithToolResult(query=query,skill_instructions=skill_instructions,partial_response=partial_response,tool_name=tool_name,tool_result=tool_result,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="FinishWithToolResult", args={
                "query": query,"skill_instructions": skill_instructions,"partial_response": partial_response,"tool_name": tool_name,"tool_result": tool_result,
            })
            return typing.cast(str, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def SelectSkill(self, query: str,skills: typing.List["types.SkillOption"],
        baml_options: BamlCallOptions = {},
    ) -> types.SkillSelection:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.SelectSkill(query=query,skills=skills,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="SelectSkill", args={
                "query": query,"skills": skills,
            })
            return typing.cast(types.SkillSelection, __result__.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def Chat(self, query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[str, str]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="Chat", args={
            "query": query,
        })
        return baml_py.BamlSyncStream[str, str](
          __result__,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExecuteSkill(self, query: str,skill_instructions: str,available_tools: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.SkillResult, types.SkillResult]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExecuteSkill", args={
            "query": query,"skill_instructions": skill_instructions,"available_tools": available_tools,
        })
        return baml_py.BamlSyncStream[stream_types.SkillResult, types.SkillResult](
          __result__,
          lambda x: typing.cast(stream_types.SkillResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.SkillResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.Resume, types.Resume]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractResume", args={
            "resume": resume,
        })
        return baml_py.BamlSyncStream[stream_types.Resume, types.Resume](
          __result__,
          lambda x: typing.cast(stream_types.Resume, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Resume, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def FinishWithToolResult(self, query: str,skill_instructions: str,partial_response: str,tool_name: str,tool_result: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[str, str]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="FinishWithToolResult", args={
            "query": query,"skill_instructions": skill_instructions,"partial_response": partial_response,"tool_name": tool_name,"tool_result": tool_result,
        })
        return baml_py.BamlSyncStream[str, str](
          __result__,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def SelectSkill(self, query: str,skills: typing.List["types.SkillOption"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.SkillSelection, types.SkillSelection]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="SelectSkill", args={
            "query": query,"skills": skills,
        })
        return baml_py.BamlSyncStream[stream_types.SkillSelection, types.SkillSelection](
          __result__,
          lambda x: typing.cast(stream_types.SkillSelection, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.SkillSelection, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def Chat(self, query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="Chat", args={
            "query": query,
        }, mode="request")
        return __result__
    def ExecuteSkill(self, query: str,skill_instructions: str,available_tools: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExecuteSkill", args={
            "query": query,"skill_instructions": skill_instructions,"available_tools": available_tools,
        }, mode="request")
        return __result__
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractResume", args={
            "resume": resume,
        }, mode="request")
        return __result__
    def FinishWithToolResult(self, query: str,skill_instructions: str,partial_response: str,tool_name: str,tool_result: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="FinishWithToolResult", args={
            "query": query,"skill_instructions": skill_instructions,"partial_response": partial_response,"tool_name": tool_name,"tool_result": tool_result,
        }, mode="request")
        return __result__
    def SelectSkill(self, query: str,skills: typing.List["types.SkillOption"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="SelectSkill", args={
            "query": query,"skills": skills,
        }, mode="request")
        return __result__
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def Chat(self, query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="Chat", args={
            "query": query,
        }, mode="stream")
        return __result__
    def ExecuteSkill(self, query: str,skill_instructions: str,available_tools: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExecuteSkill", args={
            "query": query,"skill_instructions": skill_instructions,"available_tools": available_tools,
        }, mode="stream")
        return __result__
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractResume", args={
            "resume": resume,
        }, mode="stream")
        return __result__
    def FinishWithToolResult(self, query: str,skill_instructions: str,partial_response: str,tool_name: str,tool_result: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="FinishWithToolResult", args={
            "query": query,"skill_instructions": skill_instructions,"partial_response": partial_response,"tool_name": tool_name,"tool_result": tool_result,
        }, mode="stream")
        return __result__
    def SelectSkill(self, query: str,skills: typing.List["types.SkillOption"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="SelectSkill", args={
            "query": query,"skills": skills,
        }, mode="stream")
        return __result__
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))