# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (1)
# #########################################################################

class AvailableSkill(str, Enum):
    pass

# #########################################################################
# Generated classes (4)
# #########################################################################

class Compute(BaseModel):
    tool: typing_extensions.Literal['compute'] = Field(description='Must be the literal string \'compute\'.')
    expression: str = Field(description='Python math expression, e.g. \'round(47.50 * 0.18, 2)\'.')

class SkillOption(BaseModel):
    name: str
    description: str

class SkillResult(BaseModel):
    response: str = Field(description='Response text for the user. If a tool is needed, explain what you\'re computing but don\'t guess the answer.')
    tool_request: typing.Optional["Compute"] = Field(default=None, description='Optional tool call. Null if no tool is needed.')

class SkillSelection(BaseModel):
    selected_skill: typing.Optional[str] = Field(default=None, description='Skill name to activate, or null if none match.')
    reasoning: str = Field(description='One-sentence explanation.')

# #########################################################################
# Generated type aliases (1)
# #########################################################################


ToolRequest: typing_extensions.TypeAlias = "Compute"
