# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.Resume": types.Resume,
    "stream_types.Resume": stream_types.Resume,

    "types.SkillOption": types.SkillOption,
    "stream_types.SkillOption": stream_types.SkillOption,

    "types.SkillResult": types.SkillResult,
    "stream_types.SkillResult": stream_types.SkillResult,

    "types.SkillSelection": types.SkillSelection,
    "stream_types.SkillSelection": stream_types.SkillSelection,

    "types.StaffMessage": types.StaffMessage,
    "stream_types.StaffMessage": stream_types.StaffMessage,


    "types.ActionType": types.ActionType,

}